<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <meta name="Description" CONTENT="pukiwiki テキストを markdown テキストに変換するサイトです" />
        <meta name="Keywords" content="pukiwiki,markdown,変換" />
        <title>pukiwiki テキストを markdown テキストに変換 - pukiwiki2markdown -</title>
        <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
        <!-- Global site tag (gtag.js) - Google Analytics -->
        <script async src="https://www.googletagmanager.com/gtag/js?id=UA-119237671-1"></script>
        <script>
            window.dataLayer = window.dataLayer || [];
            function gtag(){dataLayer.push(arguments);}
            gtag('js', new Date());

            gtag('config', 'UA-119237671-1');
        </script>
        <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
        <script>
          (adsbygoogle = window.adsbygoogle || []).push({
            google_ad_client: "ca-pub-6253685297779552",
            enable_page_level_ads: true
          });
        </script>
    </head>
    <body>
        <div id="app"></div>
        <script type="text/javascript" src="js/bundle.js"></script>
    </body>
</html>
